### ISSUE TITLE
Action meta

### ISSUE THREAD

**Issue by klee0kai** [klee0kai/ci_tools#2]
# Feature 

Prepare action meta. 
Support simple action import 

```yaml
jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - uses: klee0kai/ci_tools@action_meta
        with:
          args: "-h"
```
